name: Trigger auto deployment for ragorbegithub

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ragorbegithub-AutoDeployTrigger-c0c05c5e-3303-4ed0-a87d-66228ac2573f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RAGORBEGITHUB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RAGORBEGITHUB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RAGORBEGITHUB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.RAGORBEGITHUB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RAGORBEGITHUB_REGISTRY_PASSWORD }}
          containerAppName: ragorbegithub
          resourceGroup: NetworkWatcherRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


